# Generated by Django 2.2.7 on 2019-11-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude', max_length=100)),
                ('longitude', models.FloatField(help_text='Longitude', max_length=100)),
                ('unique_Squirrel_ID', models.CharField(help_text='Squirrel_ID', max_length=50)),
                ('shift', models.CharField(choices=[('pm', 'PM'), ('am', 'AM'), ('other', 'Other')], default='other', max_length=3)),
                ('date', models.DateField(help_text='Date you saw it')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('unknown', 'Unknown or Blank')], default='unknown', max_length=20)),
                ('primary_fur_color', models.CharField(choices=[('black', 'Black'), ('cinamon', 'Cinnamon'), ('gray', 'Gray'), ('other', 'Unknown or Other')], default='other', max_length=20)),
                ('location', models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane'), ('other', 'Other')], default='other', max_length=50)),
                ('specific_location', models.CharField(help_text='Specific Location', max_length=1000)),
                ('running', models.BooleanField(default=False, help_text='Whether running?')),
                ('chasing', models.BooleanField(default=False, help_text='Whether chasing?')),
                ('climbing', models.BooleanField(default=False, help_text='Whether climbing?')),
                ('eating', models.BooleanField(default=False, help_text='Whether eating?')),
                ('foraging', models.BooleanField(default=False, help_text='Whether foraging?')),
                ('other_activities', models.CharField(help_text='Other Activities', max_length=1000)),
                ('kuks', models.BooleanField(default=False, help_text='Whether Kuks?')),
                ('quaas', models.BooleanField(default=False, help_text='Whether Quaas?')),
                ('moans', models.BooleanField(default=False, help_text='Whether Moans?')),
                ('tail_flags', models.BooleanField(default=False, help_text='Whether Tail Flags?')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Whether Tail Twitches?')),
                ('approaches', models.BooleanField(default=False, help_text='Whether Approaches?')),
                ('indifferent', models.BooleanField(default=False, help_text='Whether indifferent?')),
                ('runs_from', models.BooleanField(default=False, help_text='Whether run from?')),
            ],
        ),
    ]
