# Generated by Django 2.2.7 on 2019-11-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sightings',
            new_name='Sighting',
        ),
    ]
