# Generated by Django 2.2.7 on 2019-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker', '0002_auto_20191127_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='unique_Squirrel_ID',
        ),
        migrations.AddField(
            model_name='sighting',
            name='unique_squirrel_ID',
            field=models.CharField(help_text='Squirrel_ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='shift',
            field=models.CharField(choices=[('pm', 'PM'), ('am', 'AM'), ('other', 'Other')], default='other', max_length=5),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=1000),
        ),
    ]
